# Generated by Django 3.2.6 on 2022-07-29 15:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_delete_role'),
        ('consultancy', '0010_consultancy_brochure'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('portal', models.BooleanField(default=False)),
                ('role_name', models.CharField(max_length=100)),
                ('permission_list', models.JSONField()),
                ('consultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_role', to='consultancy.consultancy')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_role', to='institute.institute')),
            ],
            options={
                'unique_together': {('institute', 'consultancy', 'portal', 'role_name')},
            },
        ),
    ]
