# Generated by Django 3.2.6 on 2022-07-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0010_consultancy_brochure'),
        ('institute', '0008_delete_role'),
        ('staff', '0002_rolebase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolebase',
            old_name='role_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='rolebase',
            unique_together={('institute', 'consultancy', 'portal', 'name')},
        ),
    ]
