# Generated by Django 3.2.6 on 2022-07-30 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0010_consultancy_brochure'),
        ('staff', '0004_auto_20220730_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffposition',
            name='consultancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_staff_role', to='consultancy.consultancy'),
        ),
        migrations.AddField(
            model_name='staffposition',
            name='portal',
            field=models.BooleanField(default=False),
        ),
    ]
