# Generated by Django 3.2.6 on 2022-07-30 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_alter_institutestaff_role'),
        ('staff', '0005_auto_20220730_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffposition',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_staff_role', to='institute.institute'),
        ),
        migrations.AddField(
            model_name='staffposition',
            name='permission_list',
            field=models.JSONField(default=[]),
        ),
    ]
