# Generated by Django 3.2.6 on 2022-08-09 12:36

import apps.comment.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute_course', '0026_alter_instituteapply_institute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_delete_applicationcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationComments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('text_comment', models.TextField()),
                ('file_comment', models.FileField(default='consultancy/cover_image/default_cover_image.png', upload_to=apps.comment.utils.upload_comment_image_to)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.instituteapply')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.applicationcomments')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
