# Generated by Django 3.2.6 on 2022-08-09 12:58

import apps.comment.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_applicationcomments_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcomments',
            name='file_comment',
            field=models.FileField(blank=True, default='consultancy/cover_image/default_cover_image.png', null=True, upload_to=apps.comment.utils.upload_comment_image_to),
        ),
        migrations.AlterField(
            model_name='applicationcomments',
            name='text_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
