# Generated by Django 3.2.6 on 2022-08-09 13:14

import apps.comment.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20220809_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcomments',
            name='file_comment',
            field=models.FileField(blank=True, null=True, upload_to=apps.comment.utils.upload_comment_image_to),
        ),
    ]
