# Generated by Django 3.2.6 on 2022-08-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_alter_applicationcomments_file_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcomments',
            name='user_type',
            field=models.CharField(blank=True, choices=[('portal_user', 'portal_user'), ('institute_user', 'institute_user'), ('consultancy_user', 'consultancy_user'), ('student_user', 'student_user')], max_length=100, null=True),
        ),
    ]
