# Generated by Django 3.2.6 on 2022-07-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='position_lidership',
            new_name='position_leadership',
        ),
    ]
