# Generated by Django 3.2.6 on 2022-05-30 12:29

import apps.core.validators
import apps.studentIdentity.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('citizenship_number', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(blank=True)),
                ('issue_from', models.CharField(blank=True, max_length=200)),
                ('front_page', models.ImageField(upload_to=apps.studentIdentity.utils.upload_student_identity_image_to, validators=[apps.core.validators.ImageValidator()])),
                ('back_page', models.ImageField(upload_to=apps.studentIdentity.utils.upload_student_identity_image_to, validators=[apps.core.validators.ImageValidator()])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('passport_number', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(blank=True)),
                ('expire_date', models.DateField(blank=True)),
                ('issue_from', models.CharField(blank=True, max_length=200)),
                ('passport_image', models.ImageField(upload_to=apps.studentIdentity.utils.upload_student_identity_image_to, validators=[apps.core.validators.ImageValidator()])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
