# Generated by Django 3.2.6 on 2022-07-02 16:57

import apps.institute.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to=apps.institute.utils.upload_brochure),
        ),
    ]
