# Generated by Django 3.2.6 on 2022-07-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_institute_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutestaff',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institutestaff',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
