# Generated by Django 3.2.6 on 2022-07-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20220703_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
