# Generated by Django 3.2.6 on 2022-07-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
