# Generated by Django 3.2.6 on 2022-08-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_alter_institutestaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='name',
            field=models.CharField(choices=[('facebook', 'facebook'), ('youtube', 'youtube'), ('linkedin', 'linkedin'), ('instagram', 'instagram')], max_length=100),
        ),
    ]
