# Generated by Django 3.2.6 on 2022-06-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultancycourse',
            old_name='concurrent',
            new_name='current',
        ),
    ]
