# Generated by Django 3.2.6 on 2022-06-18 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0009_consultancysocialmedialink'),
        ('consultancy_course', '0003_rename_current_consultancycourse_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancycourse',
            name='consultancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_course', to='consultancy.consultancy'),
        ),
    ]
