# Generated by Django 3.2.6 on 2022-05-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultancy', '0001_initial'),
        ('institute', '0001_initial'),
        ('academic', '0002_initial'),
        ('students', '0001_initial'),
        ('studentIdentity', '0001_initial'),
        ('institute_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteapply',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.faculty'),
        ),
        migrations.AddField(
            model_name='commentapplicationinstitute',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute_course.instituteapply'),
        ),
        migrations.AddField(
            model_name='commentapplicationinstitute',
            name='institute_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute.institutestaff'),
        ),
        migrations.AddField(
            model_name='commentapplicationconsultancy',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute_course.instituteapply'),
        ),
        migrations.AddField(
            model_name='commentapplicationconsultancy',
            name='consultancy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy.consultancystaff'),
        ),
        migrations.AddField(
            model_name='addscholorshipincourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute_course.institutecourse'),
        ),
        migrations.AddField(
            model_name='addscholorshipincourse',
            name='scholorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institutescholorship'),
        ),
        migrations.AddField(
            model_name='accessstudentsop',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.institutecourse'),
        ),
        migrations.AddField(
            model_name='accessstudentsop',
            name='sop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studentsop'),
        ),
        migrations.AddField(
            model_name='accessstudentsop',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='accessstudentlor',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.institutecourse'),
        ),
        migrations.AddField(
            model_name='accessstudentlor',
            name='lor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studentlor'),
        ),
        migrations.AddField(
            model_name='accessstudentlor',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='accessstudentidentity',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentIdentity.citizenship'),
        ),
        migrations.AddField(
            model_name='accessstudentidentity',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_student_identity', to='institute_course.institutecourse'),
        ),
        migrations.AddField(
            model_name='accessstudentidentity',
            name='passport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentIdentity.passport'),
        ),
        migrations.AddField(
            model_name='accessstudentidentity',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='accessstudentessay',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.institutecourse'),
        ),
        migrations.AddField(
            model_name='accessstudentessay',
            name='essay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.personalessay'),
        ),
        migrations.AddField(
            model_name='accessstudentessay',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='accessofacademicdocument',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academic'),
        ),
        migrations.AddField(
            model_name='accessofacademicdocument',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_student_academic', to='institute_course.institutecourse'),
        ),
        migrations.AddField(
            model_name='accessofacademicdocument',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='institutecourse',
            unique_together={('course', 'institute')},
        ),
        migrations.AlterUniqueTogether(
            name='instituteapply',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='accessstudentsop',
            unique_together={('course', 'sop')},
        ),
        migrations.AlterUniqueTogether(
            name='accessstudentlor',
            unique_together={('course', 'lor')},
        ),
        migrations.AlterUniqueTogether(
            name='accessstudentidentity',
            unique_together={('course', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='accessstudentessay',
            unique_together={('course', 'essay')},
        ),
        migrations.AlterUniqueTogether(
            name='accessofacademicdocument',
            unique_together={('course', 'academic')},
        ),
    ]
