# Generated by Django 3.2.6 on 2022-06-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessOfAcademicDocument',
        ),
    ]
