# Generated by Django 3.2.6 on 2022-06-09 13:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('institute_course', '0003_delete_accessofacademicdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedAcademicDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academic')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_student_academic', to='institute_course.instituteapply')),
            ],
            options={
                'unique_together': {('application', 'academic')},
            },
        ),
    ]
