# Generated by Django 3.2.6 on 2022-06-09 13:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studentIdentity', '0002_initial'),
        ('institute_course', '0004_checkedacademicdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckStudentIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_student_aidentity', to='institute_course.instituteapply')),
                ('citizenship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentIdentity.citizenship')),
                ('passport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentIdentity.passport')),
            ],
            options={
                'unique_together': {('application', 'citizenship')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='accessstudentidentity',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='accessstudentidentity',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='accessstudentidentity',
            name='course',
        ),
        migrations.RemoveField(
            model_name='accessstudentidentity',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='accessstudentidentity',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='accessstudentlor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='accessstudentlor',
            name='course',
        ),
        migrations.RemoveField(
            model_name='accessstudentlor',
            name='lor',
        ),
        migrations.RemoveField(
            model_name='accessstudentlor',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='accessstudentsop',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='accessstudentsop',
            name='course',
        ),
        migrations.RemoveField(
            model_name='accessstudentsop',
            name='sop',
        ),
        migrations.RemoveField(
            model_name='accessstudentsop',
            name='student',
        ),
        migrations.DeleteModel(
            name='AccessStudentEssay',
        ),
        migrations.DeleteModel(
            name='AccessStudentIdentity',
        ),
        migrations.DeleteModel(
            name='AccessStudentLor',
        ),
        migrations.DeleteModel(
            name='AccessStudentSop',
        ),
    ]
