# Generated by Django 3.2.6 on 2022-06-09 13:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('institute_course', '0005_auto_20220609_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkstudentidentity',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_student_identity', to='institute_course.instituteapply'),
        ),
        migrations.CreateModel(
            name='CheckedStudentLor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_student_lor', to='institute_course.instituteapply')),
                ('lor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studentlor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
