# Generated by Django 3.2.6 on 2022-06-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0007_checkedstudentessay_checkedstudentsop'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkedacademicdocument',
            unique_together=set(),
        ),
    ]
