# Generated by Django 3.2.6 on 2022-06-13 15:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0008_consultancy_rating'),
        ('institute', '0002_initial'),
        ('institute_course', '0008_alter_checkedacademicdocument_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('verify', 'verify'), ('accept', 'accept'), ('reject', 'reject'), ('pending', 'pending'), ('applied', 'applied')], default='applied', max_length=20)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.instituteapply')),
                ('consultancy_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy.consultancystaff')),
                ('institute_use', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute.institutestaff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
