# Generated by Django 3.2.6 on 2022-06-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0011_auto_20220613_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituteapply',
            name='action_consultancy_user',
        ),
        migrations.RemoveField(
            model_name='instituteapply',
            name='action_institute_user',
        ),
    ]
