# Generated by Django 3.2.6 on 2022-06-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0012_auto_20220613_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituteapply',
            name='action_data',
        ),
    ]
