# Generated by Django 3.2.6 on 2022-06-13 18:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0008_consultancy_rating'),
        ('institute_course', '0014_remove_applyaction_consultancy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteapply',
            name='action_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_institute', to='institute_course.applyaction'),
        ),
        migrations.CreateModel(
            name='ActionApplyByConsultancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('verify', 'verify'), ('accept', 'accept'), ('reject', 'reject'), ('pending', 'pending'), ('applied', 'applied')], default='applied', max_length=20)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.instituteapply')),
                ('consultancy_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy.consultancystaff')),
            ],
            options={
                'db_table': 'consultancy_action',
            },
        ),
        migrations.AddField(
            model_name='instituteapply',
            name='consultancy_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_consultancy', to='institute_course.actionapplybyconsultancy'),
        ),
    ]
