# Generated by Django 3.2.6 on 2022-06-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0015_auto_20220613_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyaction',
            old_name='institute_use',
            new_name='institute_user',
        ),
    ]
