# Generated by Django 3.2.6 on 2022-06-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0018_institutecourse_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutecourse',
            name='mode',
            field=models.CharField(choices=[('full_time', 'full_time'), ('part_time', 'part_time'), ('both', 'both')], default='', max_length=100),
        ),
    ]
