# Generated by Django 3.2.6 on 2022-07-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0021_alter_institutecourse_fee_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutecourse',
            name='qualification',
            field=models.CharField(blank=True, choices=[('school', 'school'), ('high_school', 'high_school'), ('undergraduate', 'undergraduate'), ('graduate', 'graduate'), ('post_graduate', 'post_graduate')], default='', max_length=100, null=True),
        ),
    ]
