# Generated by Django 3.2.6 on 2022-07-31 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0023_instituteapply_institute_staff_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteapply',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.institutecourse'),
        ),
    ]
