# Generated by Django 3.2.6 on 2022-07-31 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0024_alter_instituteapply_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentapplicationinstitute',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.instituteapply'),
        ),
    ]
