# Generated by Django 3.2.6 on 2022-08-07 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_alter_institutestaff_role'),
        ('institute_course', '0025_alter_commentapplicationinstitute_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteapply',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_institute', to='institute.institute'),
        ),
    ]
