# Generated by Django 3.2.6 on 2022-08-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0026_alter_instituteapply_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteapply',
            name='request_for_application_fee',
            field=models.BooleanField(default=False),
        ),
    ]
