# Generated by Django 3.2.6 on 2022-08-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0029_auto_20220827_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherfile',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
