# Generated by Django 3.2.6 on 2022-09-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0030_voucherfile_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherfile',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applyaction',
            name='action',
            field=models.CharField(choices=[('verify', 'verify'), ('accept', 'accept'), ('reject', 'reject'), ('cancel', 'cancel'), ('pending', 'pending'), ('applied', 'applied'), ('payment_requested', 'payment_requested'), ('payment_verify', 'payment_verify')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='instituteapply',
            name='action',
            field=models.CharField(choices=[('verify', 'verify'), ('accept', 'accept'), ('reject', 'reject'), ('cancel', 'cancel'), ('pending', 'pending'), ('applied', 'applied'), ('payment_requested', 'payment_requested'), ('payment_verify', 'payment_verify')], default='applied', max_length=20),
        ),
    ]
