# Generated by Django 3.2.6 on 2022-06-26 07:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_studentmodel_user'),
        ('consultancy', '0009_consultancysocialmedialink'),
        ('review', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('review', models.TextField(blank=True)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('consultancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.consultancy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.studentmodel')),
            ],
            options={
                'unique_together': {('student', 'consultancy')},
            },
        ),
    ]
