# Generated by Django 3.2.6 on 2022-07-26 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultancy', '0010_consultancy_brochure'),
        ('institute', '0005_institute_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('portal', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.JSONField()),
                ('consultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_role', to='consultancy.consultancy')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_role', to='institute.institute')),
            ],
            options={
                'db_table': 'staff_role',
            },
        ),
    ]
