# Generated by Django 3.2.6 on 2022-06-11 07:22

import apps.linkage.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0002_initial'),
        ('consultancy', '0007_consultancy_consultancy_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linkage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACCEPT', 'accept'), ('REJECT', 'reject')], max_length=10)),
                ('consultancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.consultancy')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkageDocs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to=apps.linkage.utils.upload_linkage_docs)),
                ('linkage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkage.linkage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
