# Generated by Django 3.2.6 on 2022-06-18 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_initial'),
        ('consultancy', '0009_consultancysocialmedialink'),
        ('linkage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkage',
            name='consultancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkage_consultancy', to='consultancy.consultancy'),
        ),
        migrations.AlterField(
            model_name='linkage',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkage_institute', to='institute.institute'),
        ),
    ]
