# Generated by Django 3.2.6 on 2022-08-14 08:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0010_alter_institutestaff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('account_no', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=300)),
                ('account_name', models.CharField(max_length=300)),
                ('bank_name', models.CharField(max_length=200)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(choices=[('KHALTI', 'KHALTI'), ('ESEWA', 'ESEWA')], max_length=200)),
                ('provider_id', models.CharField(max_length=200)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
