# Generated by Django 3.2.6 on 2022-08-27 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('icon', models.FileField(upload_to='')),
                ('name', models.CharField(choices=[('KHALTI', 'KHALTI'), ('ESEWA', 'ESEWA')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='provider',
            name='name',
        ),
    ]
