# Generated by Django 3.2.6 on 2022-08-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0003_auto_20220827_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_method.providername'),
        ),
    ]
