# Generated by Django 3.2.6 on 2022-08-27 12:58

import apps.payment_method.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0004_provider_provider_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='provider_name',
        ),
        migrations.AlterField(
            model_name='providername',
            name='icon',
            field=models.FileField(upload_to=apps.payment_method.utils.upload_voucher_icon),
        ),
    ]
