# Generated by Django 3.2.6 on 2022-08-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0006_provider_provider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('REGISTRATION_FEE', 'REGISTRATION_FEE')], max_length=200, null=True),
        ),
    ]
