# Generated by Django 3.2.6 on 2022-08-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0007_transaction_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
