# Generated by Django 3.2.6 on 2022-05-30 12:29

import apps.core.fields
import apps.core.validators
import apps.students.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteProfileTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('complete_address', models.BooleanField(default=False)),
                ('complete_academic_detail', models.BooleanField(default=False)),
                ('complete_parents_detail', models.BooleanField(default=False)),
                ('complete_citizenship_detail', models.BooleanField(default=False)),
                ('complete_passport_field', models.BooleanField(default=False)),
                ('complete_sop_field', models.BooleanField(default=False)),
                ('complete_personalessay_field', models.BooleanField(default=False)),
                ('complete_lor_field', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavouriteInstitute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteViewers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('nationality', models.CharField(choices=[('afghan', 'Afghan'), ('albanian', 'Albanian'), ('Algerian', 'Algerian'), ('Argentinian', 'Argentinian'), ('Australian', 'Australian'), ('Austrian', 'Austrian'), ('Bangladeshi', 'Bangladeshi'), ('Belgian', 'Belgian'), ('Bolivian', 'Bolivian'), ('Batswana', 'Batswana'), ('nepales', 'nepalies'), ('indian', 'indian')], default='nepales', max_length=20)),
                ('state_provision', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('fullname', models.CharField(max_length=250)),
                ('contact', apps.core.fields.PhoneNumberField(max_length=20)),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('image', models.ImageField(default='student/image/default_logo.png', upload_to=apps.students.utils.upload_student_image_to, validators=[apps.core.validators.ImageValidator()])),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='male', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
