# Generated by Django 3.2.6 on 2022-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaddress',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A RhD positive (A+)', 'A+'), ('A RhD negative (A-)', 'A-'), ('B RhD positive (B+)', 'B+'), ('B RhD negative (B-)', 'B-'), ('O RhD positive (O+)', 'O+'), ('O RhD negative (O-)', 'O-'), ('AB RhD positive (AB+)', 'AB+'), ('AB RhD negative (AB-)', 'AB-')], max_length=50, null=True),
        ),
    ]
