# Generated by Django 3.2.6 on 2022-06-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20220622_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaddress',
            name='nationality',
        ),
        migrations.AddField(
            model_name='studentaddress',
            name='type',
            field=models.CharField(blank=True, choices=[('permanent', 'PERMANENT'), ('temporary', 'TEMPORARY')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='nationality',
            field=models.CharField(choices=[('afghan', 'Afghan'), ('albanian', 'Albanian'), ('Algerian', 'Algerian'), ('Argentinian', 'Argentinian'), ('Australian', 'Australian'), ('Austrian', 'Austrian'), ('Bangladeshi', 'Bangladeshi'), ('Belgian', 'Belgian'), ('Bolivian', 'Bolivian'), ('Batswana', 'Batswana'), ('nepales', 'nepalies'), ('indian', 'indian')], default='', max_length=20),
        ),
    ]
