# Generated by Django 3.2.6 on 2022-06-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20220622_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddress',
            name='type',
            field=models.CharField(blank=True, choices=[('permanent', 'PERMANENT'), ('temporary', 'TEMPORARY')], default='PERMANENT', max_length=50, null=True),
        ),
    ]
