# Generated by Django 3.2.6 on 2022-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentaddress_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddress',
            name='student',
            field=models.ForeignKey(error_messages={'unique': 'address of the user already exist'}, on_delete=django.db.models.deletion.CASCADE, related_name='address_relation', to='students.studentmodel'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50, null=True),
        ),
    ]
