# Generated by Django 3.2.6 on 2022-06-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('students', '0008_alter_studentmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.studentuser'),
        ),
    ]
