# Generated by Django 3.2.6 on 2022-06-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_studentaddress_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddress',
            name='student',
            field=models.OneToOneField(error_messages={'unique': 'address of the user already exist'}, on_delete=django.db.models.deletion.CASCADE, related_name='address_relation', to='students.studentmodel'),
        ),
    ]
