# Generated by Django 3.2.6 on 2022-05-30 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PyOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.CharField(help_text='Secret used to generate OTP.', max_length=50, verbose_name='Secret')),
                ('interval', models.IntegerField(blank=True, help_text='OTP Count, to be used in case of TOTP.', null=True, verbose_name='Interval (in seconds)')),
                ('otp', models.CharField(help_text='Generated OTP.', max_length=10, verbose_name='OTP')),
                ('purpose', models.CharField(choices=[('R', 'PasswordReset'), ('A', 'Activation'), ('P', 'PhoneNumberVerification'), ('E', 'EmailVerification'), ('2FA', 'TwoFactorAuthentication')], help_text='Purpose of OTP.', max_length=3, verbose_name='Purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
            ],
            options={
                'verbose_name': 'PyOtp',
                'verbose_name_plural': 'PyOtp',
                'default_permissions': (),
            },
        ),
    ]
