# Generated by Django 3.2.6 on 2022-05-30 12:29

import apps.blog.utils
import apps.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='consultancy/logo/default_logo.png', upload_to=apps.blog.utils.upload_blog_image_to, validators=[apps.core.validators.ImageValidator()])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstituteBlog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='institute/blog/default_logo.png', upload_to=apps.blog.utils.upload_blog_image_to, validators=[apps.core.validators.ImageValidator()])),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortalBlog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='portel/blog/default_logo.png', upload_to=apps.blog.utils.upload_blog_image_to, validators=[apps.core.validators.ImageValidator()])),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortalBlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='institute/blog/default_logo.png', upload_to=apps.blog.utils.upload_blog_image_to, validators=[apps.core.validators.ImageValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
