# Generated by Django 3.2.6 on 2022-06-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_consultancyblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancyblog',
            name='summary',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='instituteblog',
            name='summary',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='portalblog',
            name='summary',
            field=models.CharField(default='', max_length=200),
        ),
    ]
