# Generated by Django 3.2.6 on 2022-05-30 12:29

import apps.consultancy.utils
import apps.core.fields
import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('contact', apps.core.fields.PhoneNumberField(max_length=20)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('website', models.URLField()),
                ('logo', models.ImageField(default='consultancy/logo/default_logo.png', upload_to=apps.consultancy.utils.upload_consultancy_logo_to, validators=[apps.core.validators.ImageValidator()])),
                ('cover_image', models.ImageField(default='consultancy/cover_image/default_cover_image.png', upload_to=apps.consultancy.utils.upload_consultancy_cover_image_to, validators=[apps.core.validators.ImageValidator()])),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultancyStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(default='consultancy_staff/photo/default_logo.png', upload_to=apps.consultancy.utils.upload_consultancy_staff_image_to, validators=[apps.core.validators.ImageValidator()])),
                ('consultancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.consultancy')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffposition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
