# Generated by Django 3.2.6 on 2022-06-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0003_consultancy_consultancy_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancy',
            name='consultancy_email',
        ),
    ]
