# Generated by Django 3.2.6 on 2022-06-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0004_remove_consultancy_consultancy_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='constantly_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
