# Generated by Django 3.2.6 on 2022-06-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0006_remove_consultancy_constantly_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='consultancy_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
