# Generated by Django 3.2.6 on 2022-06-11 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0007_consultancy_consultancy_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
