# Generated by Django 3.2.6 on 2022-07-03 09:05

import apps.institute.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0009_consultancysocialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to=apps.institute.utils.upload_brochure),
        ),
    ]
