# Generated by Django 3.2.6 on 2022-06-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_settings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='two_fa',
            field=models.BooleanField(default=False),
        ),
    ]
