# Generated by Django 3.2.6 on 2022-05-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsop',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='studentlor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='personalessay',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='academic',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AddConstraint(
            model_name='academic',
            constraint=models.UniqueConstraint(fields=('student', 'level'), name='student academic'),
        ),
    ]
