# Generated by Django 3.2.6 on 2022-05-31 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_initial'),
        ('counselling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutecounselling',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institute.institutestaff'),
        ),
        migrations.AddField(
            model_name='institutecounselling',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='institutecounselling',
            name='status',
            field=models.CharField(choices=[('START', 'start'), ('COMPLETE', 'complete'), ('NOT STARTED', 'not_start')], default='not_start', max_length=100),
        ),
    ]
