# Generated by Django 3.2.6 on 2022-05-31 15:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0002_initial'),
        ('counselling', '0003_alter_institutecounselling_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('counselling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.institutecounselling')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.institutecourse')),
            ],
            options={
                'unique_together': {('counselling', 'course')},
            },
        ),
    ]
