# Generated by Django 3.2.6 on 2022-06-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0004_interestedcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutecounselling',
            old_name='physical_counelling',
            new_name='physical_counselling',
        ),
    ]
