# Generated by Django 3.2.6 on 2022-06-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0005_rename_physical_counelling_institutecounselling_physical_counselling'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institutecounselling',
            unique_together=set(),
        ),
    ]
