# Generated by Django 3.2.6 on 2022-06-26 07:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_studentmodel_user'),
        ('consultancy', '0009_consultancysocialmedialink'),
        ('counselling', '0006_alter_institutecounselling_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyCounselling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('education_level', models.CharField(choices=[('school', 'school'), ('high_school', 'high_school'), ('undergraduate', 'undergraduate'), ('graduate', 'graduate'), ('post_graduate', 'post_graduate')], max_length=200)),
                ('which_time', models.DateTimeField(blank=True)),
                ('physical_counselling', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('START', 'start'), ('COMPLETE', 'complete'), ('NOT STARTED', 'not_start')], default='not_start', max_length=100)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy.consultancystaff')),
                ('consultancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.consultancy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
