# Generated by Django 3.2.6 on 2022-07-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0008_testjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutecounselling',
            name='comment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
