# Generated by Django 3.2.6 on 2022-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0009_institutecounselling_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancycounselling',
            name='status',
            field=models.CharField(choices=[('START', 'START'), ('COMPLETE', 'COMPLETE'), ('NOT_STARTED', 'NOT_STARTED')], default='not_start', max_length=100),
        ),
        migrations.AlterField(
            model_name='institutecounselling',
            name='status',
            field=models.CharField(choices=[('START', 'START'), ('COMPLETE', 'COMPLETE'), ('NOT_STARTED', 'NOT_STARTED')], default='not_start', max_length=100),
        ),
    ]
