# Generated by Django 3.2.6 on 2022-06-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
