# Generated by Django 3.2.6 on 2022-06-12 04:45

import apps.core.validators
import apps.gallery.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0008_consultancy_rating'),
        ('gallery', '0003_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('approve', models.BooleanField(default=False)),
                ('image', models.ImageField(default='consultancy/logo/default_logo.png', upload_to=apps.gallery.utils.upload_gallery_image_to, validators=[apps.core.validators.ImageValidator()])),
                ('consultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultancy.consultancy')),
                ('uploaded_image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy.consultancystaff')),
            ],
            options={
                'db_table': 'consultancy_galleries',
            },
        ),
    ]
