# Generated by Django 3.2.6 on 2022-07-20 13:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0005_institute_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('course', models.JSONField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_affiliation', to='institute.institute')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_affiliation', to='institute.institute')),
            ],
            options={
                'unique_together': {('institute', 'university')},
            },
        ),
    ]
