# Generated by Django 3.2.6 on 2022-07-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
