# Generated by Django 3.2.6 on 2022-05-30 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultancy', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troubleshoot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('ASSIGNED', 'Assigned'), ('VIEWED', 'Viewed'), ('SOLVED', 'Solved'), ('ONPROGRESS', 'On progress'), ('UNRESOLVED', 'Unresolved')], default='RECEIVED', max_length=20)),
                ('troubleshoot_type', models.CharField(choices=[('BILLING', 'Billing'), ('TECHNICAL', 'Technical')], max_length=10)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consultancy.consultancystaff')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.portalstaff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingTroubleshoot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('trouble_shot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='troubleshooting.troubleshoot')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
