# This is a basic workflow to help you get started with Actions

name: dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Connects to ssh server all the secrets have been added to repo's settings/secrets
      - name: cloning repo and running docker on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # Ip address of server
          ############################
          #  $ssh-keygen
          #  $cat .ssh/id_rsa.pub - this is the public key

          # I copied the public key and added to my githubs' SSH and GPG keys to allow the server to clone
          # this repo.

          #  $nano .ssh/authorized_keys -here I copied and pasted the above the public key
          #  $chmod 700 .ssh/authorized_keys

          #  $cat .ssh/id_rsa -this is the private key which i added to this repo's settings/secrets as SSH_KEY
          ################################
          key: ${{secrets.SSH_KEY}} #ssh private key obtained by running ssh-keygen
          username: ${{secrets.SSH_USERNAME}} #user of the server

          script: |
            cd backend/tuteeline-backend
            echo cloning successful
            git pull origin master
            docker rm -f core_app || true
            echo previous container removed
            docker-compose up --build -d 
            echo docker built successfully with tag core_app
            docker image prune -a -f || true
